### ISSUE TITLE
One pixel gap between items

### ISSUE THREAD

**Issue by agispas** [Vestride/Shuffle#10]
Hi,

First, congrats for your plugin !
I am having an weird issue, after I initilalize the plugins it adds a weird one pixel gap between my last set of thumbnails.

I've noticed that if I remove the vertical scrollbar from the browser with "overflow-y:hidden" then the gap disappear.This is happening just in Chrome, in Firefox works perfectly. 
Any idea how can I fix this ? 

I'm trying for hours to figure out how can I fix this...
Here is a <a href="www.catexcomp.ro/nevermore/test.html">link </a>with a test page to see exactly what I'm trying to say.

**Comment by jashwant** [comment]
@Vestride ,

I notice that `x` and `y` values in `transform` are always integers. 

I am not sure, but can rounding off the values be the reason for this gap ?

https://github.com/Vestride/Shuffle/blob/master/src/layout.js#L108

**Comment by Vestride** [comment]
I think my explanation above is the reason for the gap.

You don't want sub-pixel values inside `translate()` because then your items will be blurry because they will be sitting between pixels.

**Comment by jashwant** [comment]
So, it cannot be fixed ? Can `columnWidth` work with mediaquery breakpoints ?

I do see that isotope uses top and left, may be that's why they can use subpixels.  Thanks for explaining.

**Comment by Vestride** [comment]
You can try the `useTransforms` option, but you won't get the scaling effect.

**Comment by jashwant** [comment]
`useTransforms` makes no difference. 

I have used your bootstrap 4 example and removed the gutter.

https://codepen.io/jashwant/pen/QgzqzL

At screen size 1226px,

<img width="1113" alt="screen shot 2017-07-12 at 12 06 00 pm" src="https://user-images.githubusercontent.com/1249309/28104832-8efee240-66fa-11e7-9581-fe40ef0b1115.png">

You can see 1px gap before 2nd and 4th column of row 1.

Grid width: 1110px
Width of each item : 277.5px  _( checked from chrome developer's tool )_

First item: 
```
top: 0;
left: 0;

```
Second item: 
```
top: 0px;
left: 278px;	
```
`left` of second item should have been 0 + 277.5px = 277.5px . And since you said we need rounding off , shouldn't it be 277px, instead of 278px ? This 278px shows a gap of 1px.

I tried `float: left` after removing `display:flex` without luck. It still shows 1px gap on multiple screen sizes.

I am using Chrome 58.0.3029.110 (64-bit) on MacOs 10.11.6

**Comment by Vestride** [comment]
Rounding `0.5` rounds up. `Math.round(0.5) // 1`. You might be thinking of `floor`, which always rounds down.

Removing `float` won't do anything because each item is `position: absolute`.

---

[I forked a test](https://codepen.io/Vestride/pen/OgrQxo) desandro made due to a [very similar issue](https://github.com/metafizzy/isotope/issues/916) in isotope and masonry and it appears that using fractional values is okay. Safari makes the text a little bolder when the element is layer-promoted though. I'll look into removing the rounding in Shuffle v5, which I'm currently working on.

For now, you _might_ be able to override the `_getItemPosition` method and provide your own calculations (you could copy what it's currently doing, but don't round the values).

I still think the best solution for now is to have a small gutter.

**Comment by jashwant** [comment]
Thanks for reopening and working on it. 

Yes, I had `floor` in head but wrote `round`. 

Thanks alot for this great plugin.

**Comment by Vestride** [comment]
Even without rounding the pixel values, most browsers will still show a gap (both top/left and translate). Edge seemed to be the only browser that didn't render gaps.

Shuffle v5 will not round item positions, so you may see smaller gaps, but they'll still appear sometimes.

Closing as can't fix. If anyone knows a workaround, please let me know!

**Comment by jashwant** [comment]
Sorry, to bother again. But I tried the fix.

Replaced
`var point = new Point(Math.round(gridSize * shortColumnIndex), Math.round(setY[shortColumnIndex]));`

with
`var point = new Point(gridSize * shortColumnIndex, setY[shortColumnIndex]);
`
And I see a big gap ( more than 1px ),

<img width="1085" alt="screen shot 2017-07-16 at 1 05 32 pm" src="https://user-images.githubusercontent.com/1249309/28245575-e7a0742e-6a27-11e7-9f42-e29b426d9fec.png">

First item has `width: 269.25px`
Second item has `transform: translate(273px, 0px) scale(1)`

If I do `useTransforms: false`, I still get the `left: 273px` on second item.

It is more than 1px gap. So, I think some other calculation is wrong.

Browser has `width: 1092px`, but item container has `width: 1077px`. 4th column is being cropped. 

Testing on chrome, MacOs.

**Comment by jashwant** [comment]
I have an idea, that should fix this half pixel issue.

Can we provide a different column width to different shuffle items ? If not, can we add this functionality ?

Suppose we have a 3 column layout and total width of shuffle container is `800px` with `gutter:0`.

So, instead of giving width `266.66px ( 800/3 )` ( which raises issue of half pixel ) to every column, or rounding off ( which is not working either ), we can conclude that the width of container is not divisible by number of columns and hence 1 or more column should have more width than the other.

e.g. We can find remainder 800%3 = 2 and distribute this 2px in first 2 columns.

So, 1st column will have a width of 267px ( (int)(800/3) + 1 ), 2nd column will have a width of 267px ( (int) (800/3) + 1 ), and 3rd column will have width = 266px. This 1px difference between columns will not be visible and should fix the issue with half pixels.

I think, this may work. Can you look into it ?

**Comment by Vestride** [comment]
That may work, but would require a lot of rework internally. As this is an edge case and only a visual bug, I'm not willing to invest that much time into it and changing a lot of the code-base.

Feel free to fork this and fix it for yourself. A PR to fix this may or may not be merged, based on its level of complexity.

**Comment by jashwant** [comment]
I'll submit a PR, if I'll be able to fix it. 

Thanks for everything.

**Comment by jashwant** [comment]
In case, someone needs a quick hack.
Since, it's hard to change the column size,  I am making the container width divisible by number of columns.

It's my first attempt on ES6 class, so it may have errors.

````javascript
class Shuffle_Custom extends Shuffle {
    update(isOnlyLayout = false) {
        var num_of_columns = 4;
        var container_width = Shuffle_Custom.getSize(this.element).width;
        var mod = container_width % num_of_columns;
        if(mod !== 0) {
            // Since, width is used by plugin deeply, setting width by max-width
            this.element.style.maxWidth = (container_width - mod) + 'px';
        }
        super.update();
        // Removing max-width, so width can be updated on resize
        this.element.style.maxWidth = 'none';
    }
}
var shuffle = new Shuffle_Custom(document.querySelector('.my-shuffle-container'), {
    itemSelector: '.hentry',
    roundTransforms: false,
    // useTransforms: false,
    gutterWidth: 0
});
shuffle.update();
````

Obviously, this will have space of pixels < num_of_columns
