### ISSUE TITLE
Using jQuery `.data()` does not update `data-groups` attribute

### ISSUE THREAD

**Issue by Indiegame0** [Vestride/Shuffle#173]
How I can update the elements of grid for filters? I need to change the property of groups.
I read a old issue(it tell us to use .data()) but didn't work for me.

In the codepen, click refresh button and you will see Test5Mod don't filter correctly(in start is Bussy, now is Error but you continue see). Some console outputs to 
https://codepen.io/Indiegame/pen/vJQMBW?editors=1111

Thanks and really nice work!
(Sorry awful english)

**Comment by Vestride** [comment]
The issue here is the way jQuery handles setting new data. From the [`.data()` documentation](https://api.jquery.com/data/):
> The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery).

And here's the code you're using to update the `data-groups` attribute

```js
$(selector).data('groups', groupsNew);
```

Since Shuffle does not use jQuery, it cannot see that the jQuery's internal data object changed.

To solve this, you need to change the `data-groups` property without using the `.data()` method.

```js
$(selector).attr('data-groups', groupsNew);
```

Or without jQuery

```js
document.querySelector(selector).setAttribute('data-groups', groupsNew);
```
