### ISSUE TITLE
Items seem to be hidden when container is not visible

### ISSUE THREAD

**Issue by dangrima90** [Vestride/Shuffle#226]
First of all great job with the plugin, I've found it very easy to use and works very well! :) I'm having a small issue when the shuffle container is not visible. I don't know if this is something that is not supported or maybe some changes are needed from my end.

Basically what's happening is that the items seem to remain hidden. Below you'll find two examples, a working example with the shuffle container visible on the page, and another example with with tabs, the second tab containing the shuffle container.

**Example with visible container (working as expected):**
https://stackblitz.com/edit/js-w5uvt4

**Example with container in a hidden tab:**
https://stackblitz.com/edit/js-6ydu1e

When I inspect the elements, it seems that the items are added but they are hidden. I made this simple example to try to replicate the issue I'm having in an Angular application. In the Angular application I have the same thing is happening, basically if the shuffle container is visible I have no problems whatsoever. But if the container is hidden I'm having a few issues.

Not sure if you have an idea how this would be solved.

**Comment by dangrima90** [comment]
I've continued to investigate and found out that when the window resizes and the shuffle container is visible the items then are shown. It's as if when the container is not visible the logic to position the items is not running.

**Comment by Vestride** [comment]
You are right, positioning calculations are often broken when done from a child whose parent has `display: none`. This is because many properties [return `0` when they have an ancestor with `display: none` like `offsetWidth`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth). To get around this, you can use `visibility: hidden`, absolute positioning, or set a dimension to zero (like height) and have overflow hidden.

A couple other notes on your code:

1. You should use a real array with the `add` method.
    ```js
    shuffleInstance.add($(newTemplate));
    ```

    ```js
    shuffleInstance.add($(newTemplate).toArray());
    ```

2. [jQuery's `clone()` method](https://api.jquery.com/clone/) returns a jQuery object, so you don't need to wrap it in jQuery again. I'm using dollar signs for the variable name because that's a convention for me, but you don't have to.

    ```js
    let newTemplate = $('#new-item').find('.add-item').clone();
    $(newTemplate).find('.item-name').text(`Item ${itemIndex}`);
    ```
    ```js
    let $newTemplate = $('#new-item').find('.add-item').clone();
    $newTemplate.find('.item-name').text(`Item ${itemIndex}`);
    ```

**Comment by dangrima90** [comment]
Thanks a lot for your reply and examples that you provided. I'll review my code and see how I can solve it. Have a nice day!
