### ISSUE TITLE
Adding items

### ISSUE THREAD

**Issue by iplanwebsites** [Vestride/Shuffle#244]
Using 5.1.2, I'm having troubles adding items to the grid. I'm able to append the node to the HTML, but can't have shuffle update it's view and resize it's grid.

`shuffle.add( newlyAppendedNode )` returns errors for both DOM element or their jQuery counterpart. I had no more luck with `shuffle.update()`.
The only Shuffle method that seem to work is `shuffle.resetItems()`, which redraw everything, and obviously creates flickering.

**Comment by iplanwebsites** [comment]
Thanks for the quick response. Yes! I tried wrapping my node in an object.
Not sure if could be the problem, but I create my new dom object using `Range` and an HTML string. The code:
`
var range = document.createRange();
var item = range.createContextualFragment( html )
var appended = $('#gal').prepend( item );
var $appended = $(appended)

//then...
grid.add( [ appended] ); //bug
grid.add(  appended );   //bug
grid.add( [ $appended] );  //bug
grid.add(  $appended );   //bug

grid.resetItems(); //works! but UGLY!

`

Do you think I'd be better to add a class, to this object and then retrieve a fresh new copy from Jquery? 
The add method exist, so it's not a problem with retrieving my instance.

**Comment by Vestride** [comment]
It looks to me like you're trying to append the new item, but it's actually appending the `#gal` element. The [documentation for `prepend()`](https://api.jquery.com/prepend/) only says it returns jQuery, but I think it's going to return `$('#gal')` instead of what was prepended.

I would do what you suggested: retrieve a "fresh new copy" of the elements. You can get a real array from a jQuery object with the `.get()` method.

**Comment by iplanwebsites** [comment]
$appended is really an array of the appended items here :(
