### ISSUE TITLE
Not Able to Bind jQuery UI Slider Event With 

### ISSUE THREAD

**Issue by Behseini** [Vestride/Shuffle#255]
Can you please take a look at [This Demo](http://jsfiddle.net/tLyz4chp/1/) and let me know why I am not able to bind the dynamically checked checkboxes event to shuffle.js?

As you can see from the Demo I am checking and un-checking checkboxes from the jQuery UI Slider but this is not firing any Filter event of shuffle

This is the part to change checkboxes states
		

```js
$(function() {
  $("#slider-range").slider({
    range: true,
    min: 50,
    max: 54,
    step: 0.0001,
    values: [50, 54],
    stop: function(event, ui) {
      $("input:checkbox[name=temple]").each(function() {
        var value = this.value;
        var shouldBeChecked = value >= ui.values[0] && value <= ui.values[1];
        var wasChecked = this.checked;
        if (wasChecked !== shouldBeChecked)
          $(this)
            .prop("checked", shouldBeChecked)
            .trigger("change");
      });
    }
  });
});
```

Thanks

**Comment by Vestride** [comment]
I believe the issue is that you're trying to "trigger" the change event with jQuery, but you aren't listening to the change events with jQuery (native js `addEventListener()`). The `_handleLWidthChange` method never gets called when moving the slider, but it does when you click the checkbox manually.

A couple suggestions:
The way I would solve this is to avoid using `.trigger('change')` and instead call the `_handleLWidthChange()` method directly (and probably also change its name a little because it's no longer only an event handler).
The other way which would probably work is to listen for events with jQuery in `_bindEventListeners()`.

**Comment by Vestride** [comment]
It looks to me like you've wrapped `this` in jQuery, so you won't actually be calling the correct `_handleLWidthChange()`.

Maybe try

```js
Demo.prototype._bindEventListeners = function() {
  var onWidthChange = this._handleLWidthChange.bind(this);
  this.lwidths.forEach(function(input) {
    input.addEventListener("change", onWidthChange);
  }, this);

  $("#slider-range").slider({
    range: true,
    min: 50,
    max: 54,
    values: [50, 54],
    stop: function(event, ui) {
      $("input:checkbox[name=temple]").each(function() {
        var value = this.value;
        var shouldBeChecked = value >= ui.values[0] && value <= ui.values[1];
        var wasChecked = this.checked;
        if (wasChecked !== shouldBeChecked) {
          this.checked = shouldBeChecked;
          onWidthChange();
        }
      });
    }
  });
};
```

**Comment by Behseini** [comment]
Thanks a lots.
