### ISSUE TITLE
Question: Show concealed items

### ISSUE THREAD

**Issue by Dreamfish19** [Vestride/Shuffle#73]
Hey Vestride,

thanks for this awesome js script!

I would like to not have the concealed items deleted , but to show them with less opacity after
the ordered and filtered items.

Is that possible?

**Comment by Vestride** [comment]
Nope, sorry. You may be able to use `!important` with the `.concealed` class but that could break some things.

I think isotope supports different styles though.

**Comment by Vestride** [comment]
This is now possible with v4 because you can control the styles applied to each item before/after the transition. The 2 caveats:
1. There has to be a `transitionend` event. If you didn't want the opacity to change, you could transition something like `background-color`.
2. The visible and hidden scale for the items cannot be the exact same.

Here's how you could accomplish this now:

```js
// Before initializing Shuffle.
Shuffle.ShuffleItem.Scale.HIDDEN = 0.999;
Shuffle.ShuffleItem.Css.HIDDEN.before.opacity = 0.5
Shuffle.ShuffleItem.Css.HIDDEN.after = {} // Removes `visibility:hidden` from being set.
```

**Comment by AlessandroBuoscio** [comment]
Hi @Vestride,
i used this code but all the "hidden" element are no calculated like others, they stay in the same translate position, thereby the grid container doesn't refresh his height.

How can i solve this?

Thank you,
a.
